# golangci-lint v2 configuration
# https://golangci-lint.run/usage/configuration/
#
# NOTE: VS Code's YAML schema for golangci-lint may show errors for valid v2 config options.
# This is a VS Code schema limitation. The config is validated with `golangci-lint config path`.
# Ignore VS Code warnings for: linters-settings, exclude-rules, exclude-dirs, output options.

version: 2

linters:
  enable:
    # Mandatory linters from project rules
    - errcheck # Check for unchecked errors
    - govet # Report suspicious constructs
    - ineffassign # Detect ineffectual assignments
    - staticcheck # Advanced static analysis (includes gosimple)
    - unused # Check for unused constants, variables, functions, and types
    - misspell # Find commonly misspelled English words

    # Recommended additional linters
    - gosec # Inspect source code for security problems
    - unconvert # Remove unnecessary type conversions

  # gocyclo disabled - MCP server and parsers intentionally have complex functions

formatters:
  enable:
    - gofmt # Verify code is formatted with gofmt
    - goimports # Verify imports are formatted correctly

linters-settings:
  gocyclo:
    min-complexity: 200 # High threshold - MCP server registers many tools in single functions

  errcheck:
    check-blank: false # Allow ignoring return values with _
    check-type-assertions: false # Don't require checking type assertions
    exclude-functions:
      # Allow ignoring Close() errors in defer statements
      - (io.Closer).Close
      - (*os.File).Close
      - (net.Conn).Close
      - (*net.UDPConn).Close
      - (*github.com/moby/moby/client.Client).Close
      - (github.com/digitalocean/go-libvirt.Libvirt).Disconnect
      # Allow ignoring parse errors for best-effort parsing
      - strconv.ParseUint
      - strconv.ParseInt
      - strconv.ParseFloat
      - strconv.Atoi
      - fmt.Sscanf
      - fmt.Fprintf
      # Allow ignoring JSON marshal errors (panic-safe with valid types)
      - json.Marshal
      - json.MarshalIndent
      - (*http.ResponseWriter).Write
      - (http.ResponseWriter).Write
      - url.Parse
      - (*net.UDPConn).LocalAddr
      # Allow ignoring os operations in cleanup
      - os.Remove
      - os.RemoveAll
      - os.Chmod

  govet:
    enable-all: true
    disable:
      - fieldalignment # Struct field alignment optimization - too strict for readability
      - shadow # Variable shadowing - common pattern in Go error handling

  gosec:
    excludes:
      # G204: Subprocess launched with variable - expected for shell execution lib
      - G204
      # G304: File path provided as taint input - expected for config file reading
      - G304
      # G115: Integer overflow conversion - intentional for stats where overflow is impossible
      - G115
      # G104: Errors unhandled - covered by errcheck with better granularity
      - G104
      # G301: Directory permissions - test files need broader permissions
      - G301
      # G306: WriteFile permissions - test files use standard permissions
      - G306

run:
  timeout: 5m
  tests: false # Don't lint test files

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  exclude-dirs:
    - build
    - scripts
    - tests
  exclude-rules:
    # Exclude deprecated Docker API warnings - will be fixed in future update
    - linters:
        - staticcheck
      text: "(SA1019).*(NewClientWithOpts|WithAPIVersionNegotiation)"
    # Exclude QF1008 suggestions for embedded field selectors
    - linters:
        - staticcheck
      text: "QF1008"
    # Exclude libvirt Disconnect errors - connection cleanup best-effort
    - linters:
        - errcheck
      text: "Disconnect"
    # Exclude unused fields that are kept for future use
    - linters:
        - unused
      text: "(hostCPUTime|mu|mustMarshal)"
    # Exclude SA4031 for intentional nil checks
    - linters:
        - staticcheck
      text: "SA4031"

output:
  formats:
    colored-line-number: {}
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
