linters:
  enable:
    # Mandatory linters from project rules
    - errcheck # Check for unchecked errors
    - govet # Report suspicious constructs
    - ineffassign # Detect ineffectual assignments
    - staticcheck # Advanced static analysis (includes gosimple)
    - unused # Check for unused constants, variables, functions, and types
    - misspell # Find commonly misspelled English words
    - revive # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - gofmt # Verify code is formatted with gofmt
    - goimports # Verify imports are formatted correctly

    # Recommended additional linters
    - gocritic # Comprehensive Go source code linter
    - gocyclo # Detect cyclomatic complexity
    - dupl # Detect code duplication
    - gosec # Inspect source code for security problems
    - unconvert # Remove unnecessary type conversions

linters-settings:
  gocyclo:
    min-complexity: 150 # Relaxed - some MCP/parsing functions are intentionally complex

  dupl:
    threshold: 200 # Relaxed for similar handler patterns

  errcheck:
    check-blank: false # Allow ignoring return values with _
    check-type-assertions: true
    exclude-functions:
      # Allow ignoring Close() errors in defer statements
      - (io.Closer).Close
      - (*os.File).Close
      - (net.Conn).Close
      - (*net.UDPConn).Close
      - (*github.com/moby/moby/client.Client).Close
      - (github.com/digitalocean/go-libvirt.Libvirt).Disconnect
      # Allow ignoring parse errors for best-effort parsing
      - strconv.ParseUint
      - strconv.ParseInt
      - strconv.ParseFloat
      - strconv.Atoi
      - fmt.Sscanf
      - fmt.Fprintf
      # Allow ignoring JSON marshal errors (panic-safe with valid types)
      - json.Marshal
      - json.MarshalIndent
      - (*http.ResponseWriter).Write
      - (http.ResponseWriter).Write
      - url.Parse
      - (*net.UDPConn).LocalAddr

  govet:
    enable-all: true
    disable:
      - fieldalignment # Struct field alignment optimization - too strict for readability
      - shadow # Variable shadowing - common pattern in Go error handling

  revive:
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning

  gocritic:
    disabled-checks:
      - ifElseChain # Sometimes if-else chains are clearer than switch
      - elseif # Style preference
      - assignOp # Style preference

  gosec:
    excludes:
      # G204: Subprocess launched with variable - expected for shell execution lib
      - G204
      # G304: File path provided as taint input - expected for config file reading
      - G304
      # G115: Integer overflow conversion - intentional for stats where overflow is impossible
      - G115
      # G104: Errors unhandled - covered by errcheck with better granularity
      - G104

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  new: false

  exclude-dirs:
    - build
    - scripts
    - tests

  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
        - gocyclo
        - govet
        - gocritic
        - staticcheck
        - unused
    # Exclude deprecated Docker API warnings - will be fixed in future update
    - linters:
        - staticcheck
      text: "SA1019.*NewClientWithOpts|WithAPIVersionNegotiation"
    # Exclude libvirt Disconnect errors - connection cleanup best-effort
    - linters:
        - errcheck
      text: "l.Disconnect"
    # Exclude unused fields that are kept for future use
    - linters:
        - unused
      text: "hostCPUTime|mu.*unused"

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
