# Prettier configuration
# https://prettier.io/docs/en/options

# General
printWidth: 120
tabWidth: 2
useTabs: false
endOfLine: lf

# Markdown
proseWrap: preserve

# YAML
singleQuote: false
bracketSpacing: true

# JSON
trailingComma: all
